### PR TITLE
reading and writing files from files id

### PR DESCRIPTION
**Pull request by jcolomb**
Hi Chris,
started to work with the package. 
I debug updating a file and wrote a new function to read files directly. (based on the download function)

Note the the file you give in example does not work (for the download_files also not), maybe because the storage is github (??).
Please check for problems.

I have enough for my purpose with this, but tell me if there is anything you would like tested.

### CODE REVIEW

**Comment by chartgerink** [comment]
Thanks @jcolomb! I will check this out in the next two weeks as I hope to get around to stabilizing this package (this has been carrying on for too long and it seems like people really want to start using it).

I'll put my questions in a review, and understand you're busy too. Would still very much appreciate any feedback at that time. I'll keep you posted on this!

**Comment by jcolomb** [comment]
we are all always busy, the world so much need fixing :)
BTW I would change the name of exported function to avoid conflicts with other packages (login()would become osf_login() for example).
I will try to help as much as possible.

**Comment by jcolomb** [comment]
hey.
for osfr::path_file(),  I get warning message "No encoding supplied: defaulting to UTF-8." twice, but the file is read, work even with shiny, super cool actually: see  https://github.com/jcolomb/HCS_analysis and the app at https://github.com/jcolomb/HCS_analysis/tree/master/analysis/shiny__Analyse_data ...

**Comment by chartgerink** [comment]
Thanks for the comment! I'm sorry I've been lacking on working on this --- there is something I cannot really disclose blocking me from working on this. Hope that can be cleared up soon.

**Comment by jcolomb** [comment]
I modified the description field to make citation work. I will indeed reference to it in a paper in the near future ;)
https://www.overleaf.com/read/hxwpffyxfbzm

**Comment by bgrich** [comment]
Thanks for your contribution!

**Pull request merged**
